name = "HeteroscedasticPCA"
uuid = "5b0c0c40-6f85-415d-b828-3ce01d5b51ec"
authors = ["David Hong <dahong67@wharton.upenn.edu> and contributors"]
version = "0.1.0"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
IntervalArithmetic = "0.17"
IntervalRootFinding = "0.5"
julia = "1.2"
